"""empty message

Revision ID: 362a1a3d3e0a
Revises: 
Create Date: 2024-06-26 22:24:58.420590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362a1a3d3e0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bone_age',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('pid', sa.String(length=20), nullable=False),
    sa.Column('study_datetime', sa.DateTime(), nullable=False),
    sa.Column('predictions', sa.Text(), nullable=True),
    sa.Column('instance_datetime', sa.DateTime(), nullable=False),
    sa.Column('instance_id', sa.String(length=200), nullable=False),
    sa.Column('series_id', sa.String(length=200), nullable=False),
    sa.Column('study_id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('create_predictions_date', sa.DateTime(), nullable=True),
    sa.Column('path_image', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Wait', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bone_age')
    # ### end Alembic commands ###
